# -*- coding: utf-8 -*-
"""Proyek Analisis Data_Bike Sharing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hIQDiw5CwNZNasGB2aE8CNnB3PdARV1I

# Proyek Analisis Data: Bike Sharing
- **Nama:** Krishna Alvian Ramadhani
- **Email:** m180d4ky1416@bangkit.academy
- **ID Dicoding:** krishna_alvian_ramadhani_m180d4ky1416_tu6L

## Menentukan Pertanyaan Bisnis

- Apa hubungan cuaca dengan persewaan sepeda di hari kerja?
- Bagaimana perbedaan persewaan sepeda di hari libur dan hari kerja?

## Import Semua Packages/Library yang Digunakan
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import seaborn as sns

"""## Data Wrangling

### Gathering Data

**Load Data**
"""

hour_df = pd.read_csv("/content/hour.csv")
hour_df.head()

day_df = pd.read_csv("/content/day.csv")
day_df.head()

"""### Assessing Data"""

day_df.info()

day_df.isna().sum()

print("Jumlah duplikasi data: ", day_df.duplicated().sum())
day_df.describe()

hour_df.info()

day_df.isna().sum()

print("Jumlah duplikasi data: ", hour_df.duplicated().sum())
hour_df.describe()

"""### Cleaning Data"""

day_df.drop_duplicates(inplace=True)

print("Jumlah duplikasi: ", day_df.duplicated().sum())

"""Karena tidak ada data duplikat dan tidak ada  ada data yang perlu dihilangkan atau dibersihkan. Oleh karena itu, menghilangkan kolom dan memberikan penjelasan lebih pada kolom dari data yang digunakan agar lebih mudah dalam mengidenfitikasi suatu permasalahan bisnis"""

drop_col = ['instant', 'windspeed', 'atemp']

for i in day_df.columns:
    if i in drop_col:
        day_df.drop(labels=i, axis=1, inplace=True)

day_df.head()

# Mengubah nama kolom
day_df = day_df.rename(columns={
    'dteday': 'dateday',
    'yr': 'year',
    'mnth': 'month',
    'weathersit': 'weather',
    'temp': 'temperature',
    'hum': 'humadity',
    'cnt': 'count'
})
day_df.head()

"""Pembacaan angka diatas menjadi suatu keterangan
Month urut berdasarkan bulan Januari (1) hingga Desember (12)
Season dibagi menjadi 4 yaitu (1) Spring, (2) Summer, (3) Fall, dan (4) Winter
Weekday urut berdasarkan hari mulai dari Minggu (0) hingga Sabtu (6)
Weather dibagi menjadi 4 yaitu (1) Cerah, (2) Berawan, (3) Hujan, dan (4) Ekstrem
"""

day_df.info()

"""## Exploratory Data Analysis (EDA)

### Explore Data day_df
"""

day_df.groupby(by='weather').agg({
    'count': ['max', 'min', 'mean', 'sum']
})

day_df.groupby(by='workingday').agg({
    'count': ['max', 'min', 'mean']
})

day_df.groupby(by='holiday').agg({
    'count': ['max', 'min', 'mean', 'sum']
})

day_df.groupby(by='weekday').agg({
    'count':['max','min','mean']
})

"""## Visualization & Explanatory Analysis

### Pertanyaan 1: Apa hubungan cuaca dengan persewaan sepeda di hari kerja?
"""

plt.figure(figsize=(10, 6))
sns.boxplot(data=day_df, x='weather', y='count', hue='workingday')
plt.title('Hubungan Cuaca dengan Persewaan Sepeda di Hari Kerja')
plt.xlabel('weather')
plt.ylabel('Total Penyewa Sepeda')
plt.show()

"""### Pertanyaan 2: Bagaimana perbedaan persewaan sepeda di hari kerja dan hari biasa"""

plt.figure(figsize=(10, 6))
sns.boxplot(data=day_df, x='workingday', y='count', hue='weekday')
plt.title('perbedaan Persewaan Sepeda di Hari Kerja dan Hari Biasa')
plt.xlabel('workingday')
plt.ylabel('Total Penyewa Sepeda')
plt.show()

"""## Conclusion

- Dari hasil didapatkan kesimpulan bahwa terdapat hubungan antara persewaan sepeda dengan cuaca. Pada cuara cerah (1) dan di hari kerja pada plot didapatkan hasil yang cukup besar. Apabila di cuaca hujan (3) penyewa sepeda cukup sedikit. Oleh karena itu, dapat disimpulkan bahwa cuaca akan mempengaruhi persewaan sepeda
- Terdapat perbedaan antara persewaan di hari kerja dan hari biasa. Pada hari biasa persewaan sepeda cenderung hanya di hari Sabtu dan Minggu dengan plot yang sangat lebar. Namun, pada hari kerja plot dari hari Senin-Jumat cukup lebar.
"""

!pip freeze > requirements.txt